### PR TITLE
Don't suggest direct scraper file download

### PR DESCRIPTION
**Pull request by Phasetime**
I noticed a few people recently that read this guide and tried downloading scrapers from github like the guide recommends by `Right Click -> Save as..`. It's nowhere mentioned how to get to the raw scraper file though so people often download the HTML source instead. I think we can just avoid this problem all together and just recommend zip archive download only.

Let me know if I should change anything, as it's my first try at altering the documentation. If you still want to include the direct raw scraper download I can also write a little section on how to do that correctly.

### CODE REVIEW

**Comment by AdultSun** [comment]
I feel like dealing with zip archives and making the default "download every single scraper we have" is clunkier and less user-friendly then explaining how to download only the scrapers you may need, one at a time. It would also give users the info they need to update their scrapers one at a time as well. The whole point of the guide is to redirect everyone to StashDB, then TPDB if that doesn't work, and then only use site-specific scrapers as a last resort because they're so much more difficult to use and troubleshoot. They should really only be left to more advanced users or users who absolutely know that they need them.

I didn't explain the "Raw" thing because I just link directly to the raw page for the TPDB scraper instead under "Use ThePornDB Scraper". We can add an extra line of explanation to "Use Site-Specific Scrapers" if it helps ("make sure you click Raw at the top of the scraper's page before saving it" is likely all we'd want or need there). We can also add another hyperlink back up to the TPDB section for the rest of the steps instead of spelling them all out again. I'd rather follow that approach instead of abandoning the single download method entirely and pointing at the zip file.

Ultimately, the site-specific scraper section is short for a reason. It should be clear that it's a method intended for more advanced users so if the guide's explanation is already over you head, you're probably better off using StashDB or TPDB as recommended. Otherwise, you'll likely need to ask for help getting it to work anyways. Since each scraper is different, we're not going to be able to write a guide comprehensive enough to avoid that. We could also add an extra line at the end explaining exactly that, "Ultimately, if you're absolutely certain that using StashDB or TPDB isn't enough for what you need and the above explanation is still too confusing to you, then you'll need to ask for help," and then linking to the Discord channel for scrapers.

**Comment by DogmaDragon** [comment]
I go into step by step here on scrapers <https://docs.stashapp.cc/add-ons/scrapers/#installation>

**Comment by AdultSun** [comment]
Great, linking out to that guide should help as well.

**Comment by DogmaDragon** [comment]
@AdultSun I'll leave this to you. just merge when you are satisfied with the end result since this is your guide.

**Pull request closed without merging**
